repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        args: ["--profile", "black"]  # Align isort with black's formatting
        pass_filenames: true  # Ensures filenames are passed to isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        pass_filenames: true  # Ensures filenames are passed to black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --ignore=E203,W503,E501  # Ignore the whitespace before colon, line break before binary operator, and long lines
          - --max-line-length=120  # Set max line length to 120 characters