runtime: custom
env: flex

entrypoint: streamlit run app.py --server.port $PORT

resources:
  cpu: 0.5
  memory_gb: 0.5

automatic_scaling:
  max_num_instances: 4
  min_num_instances: 1
  max_concurrent_requests: 3