runtime: python
env: flex

runtime_config:
  operating_system: "ubuntu22"
  python_version: "3.12"

entrypoint: streamlit run app.py --server.port $PORT

resources:
  cpu: 1
  memory_gb: 1

automatic_scaling:
  max_num_instances: 1

env_variables:
  MAX_CONTENT_LENGTH: 50000000 # 50MB
  UPLOAD_TIMEOUT: 300 # 5 minutes