version: '3'
name: qodia
services:
  kodierungstool:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    networks:
      - app-network
    volumes:
      - ./data:/app/data
    environment:
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - RAPID_API_KEY=${RAPID_API_KEY}
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - streamlit
    networks:
      - app-network
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro 
networks:
  app-network:
    driver: bridge
