version: '3'
services:
  streamlit:
    container_name: qodia-kodierungstool
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    networks:
      - app-network
    volumes:
      - ./data:/app/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - streamlit
    networks:
      - app-network
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro

networks:
  app-network:
    driver: bridge