version: '3'

services:
  streamlit:
    build: .
    expose:
      - 8080
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - streamlit
    networks:
      - app-network

networks:
  app-network:
    driver: bridge