FROM nginx:alpine

# Install OpenSSL
RUN apk add --no-cache openssl

# Copy the certificate generation script
COPY scripts/generate_self_signed_cert.sh /generate_self_signed_cert.sh

# Make the script executable
RUN chmod +x /generate_self_signed_cert.sh

# Generate the self-signed certificate
RUN /generate_self_signed_cert.sh

# Copy the Nginx configuration
COPY data/nginx.conf /etc/nginx/nginx.conf

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]